# ------------------------------------------------
# Driver conf
# ------------------------------------------------

name: 'Arsys'
description: 'Arsys Baremetal Cloud Provider'
version: '1.1.5'

# FireEdge configuration (logos, metadata, etc)
fireedge:
  logo: '/fireedge/client/assets/images/providers/arsys.png'
  color: "E63329"
  operations:
    add-host: amount
    del-host: ids
    add-ip: amount
    del-ip: ids
  layout:
    provider:
      - oneform_hosts
      - type
      - operating_system
      - datacenter
    network:
      - cidr_block
