#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2025, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to register a new IP network in the IPAM. The network may
# be selected by a pool of free networks or if an specific network is requested
# its availability maybe checked by the IPAM driver.
#
# The IPAM driver must return an OpenNebula AddressRange definition, potentially
# augmented with network specific variables to be used by VMs (e.g. GATEWAYS,
# MASK...)
#
# STDIN Input:
#   - Base64 encoded XML with AR request
#
# XML format
#  <IPAM_DRIVER_ACTION_DATA>
#    <AR>
#      <TYPE>Type of the IP (ipv4/ipv6)</TYPE>
#      <PROVISION_ID>ID</PROVISION_ID>
#    </AR>
#  </IPAM_DRIVER_ACTION_DATA>
#
# The response MUST include IPAM_MAD, TYPE, IP and SIZE attributes, example:
#       AR = [
#         IPAM_MAD = "arsys",
#         TYPE = "IP4",
#         IP   = "10.0.0.1",
#         SIZE = "1",
#         DEPLOY_ID = "..",
#         EXTERNAL_IP      = "185.x.x.x",
#         NETWORK_MASK     = "255.255.255.254",
#         GATEWAY          = "10.0.0.0",
#         ARSYS_IP_ID      = "<hex32>",
#         PROVISION_ID     = "...",
#       ]
################################################################################

ONE_LOCATION = ENV['ONE_LOCATION'] unless defined?(ONE_LOCATION)

if !ONE_LOCATION
    LIB_LOCATION      ||= '/usr/lib/one'
    RUBY_LIB_LOCATION ||= '/usr/lib/one/ruby'
    GEMS_LOCATION     ||= '/usr/share/one/gems'
    DRIVERS_PATH      ||= '/var/lib/one/oneform/drivers/oneform-registry'
else
    LIB_LOCATION      ||= ONE_LOCATION + '/lib'
    RUBY_LIB_LOCATION ||= ONE_LOCATION + '/lib/ruby'
    GEMS_LOCATION     ||= ONE_LOCATION + '/share/gems'
    DRIVERS_PATH      ||= ONE_LOCATION + '/var/oneform/drivers/oneform-registry'
end

# %%RUBYGEMS_SETUP_BEGIN%%
require 'load_opennebula_paths'
# %%RUBYGEMS_SETUP_END%%

$LOAD_PATH << RUBY_LIB_LOCATION
$LOAD_PATH << File.join(DRIVERS_PATH, 'arsys/elastic')

require 'net/http'
require 'uri'
require 'json'
require 'arsys'
require 'base64'
require 'nokogiri'
require 'opennebula'
require 'opennebula/oneform_client'
require 'ipaddr'
require 'digest'

DEFAULT_PRIVATE_CIDR = '172.16.0.0/12'
DATACENTERS_PATH     = File.join(
    DRIVERS_PATH,
    'arsys',
    'terraform',
    'datacenters.json'
)

# Add ^ operator and prefix method to IPAddr
class IPAddr

    def ^(other)
        clone.set(@addr ^ other.to_i)
    end

    def prefix
        case @family
        when Socket::AF_INET
            n = IN4MASK ^ @mask_addr
            i = 32
        when Socket::AF_INET6
            n = IN6MASK ^ @mask_addr
            i = 128
        else
            raise AddressFamilyError, 'unsupported address family'
        end
        while n > 0
            n >>= 1
            i -= 1
        end
        i
    end

end

begin
    data = Nokogiri::XML(Base64.decode64(STDIN.read))

    # --------------------------------------------------------------------------
    # Get connection details for the provider
    # --------------------------------------------------------------------------
    provision_id = data.xpath('//AR/PROVISION_ID').text

    if provision_id.empty?
        STDERR.puts 'Missing provision id in address range'
        exit(-1)
    end

    client   = OneForm::Client.new
    document = client.get_provision(provision_id)

    if document.key?(:err_code)
        STDERR.puts "Error retrieving provision #{provision_id}: #{document[:message]}"
        exit(-1)
    end

    provision = document[:TEMPLATE][:PROVISION_BODY]
    document  = client.get_provider(provision[:provider_id], :include_sensitive => true)

    if document.key?(:err_code)
        STDERR.puts "Error retrieving provider #{provision[:provider_id]}: #{document[:message]}"
        exit(-1)
    end

    provider    = document[:TEMPLATE][:PROVIDER_BODY]
    connect     = provider[:connection]
    arsys_token = connect[:token]
    arsys_host  = connect[:host]

    datacenters  = JSON.parse(File.read(DATACENTERS_PATH))
    datacenter    = connect[:datacenter]
    datacenter_id = datacenters.fetch(datacenter) do
        raise "Unknown Arsys datacenter '#{datacenter}'"
    end

    # --------------------------------------------------------------------------
    # Connect to Arsys and allocate a new Public IP
    # --------------------------------------------------------------------------

    private_cidr = data.xpath('//AR/PRIVATE_CIDR').text
    private_cidr = DEFAULT_PRIVATE_CIDR if private_cidr.empty?

    cidr = IPAddr.new(private_cidr)
    mask = 0x0FFFFFFFF >> cidr.prefix

    arsys = Arsys.new(arsys_token, arsys_host)

    ip_req = { :datacenter_id => datacenter_id, :type => 'IPV4' }
    resp   = arsys.api_call('/public_ips', Net::HTTP::Post, ip_req)

    unless resp.code == '201'
        STDERR.puts "Arsys API failure, HTTP #{resp.code}, #{resp.message}, #{resp.body}"
        exit(-1)
    end

    ip_data = JSON.parse(resp.body)
    addr    = ip_data['ip']
    ip_id   = ip_data['id']

    ipmd5 = Digest::MD5.hexdigest(addr).to_i(16) & mask
    eip   = IPAddr.new(ipmd5, Socket::AF_INET)

    ipvm = (eip & mask) | cidr
    ipgw = ipvm ^ 1

    puts <<-EOF
        AR = [
            TYPE = "IP4",
            IP   = "#{ipvm}",
            SIZE = "1",
            IPAM_MAD     = "arsys",
            GATEWAY      = "#{ipgw}",
            EXTERNAL_IP  = "#{addr}",
            NETWORK_MASK = "255.255.255.254",
            ARSYS_IP_ID  = "#{ip_id}",
            PROVISION_ID = "#{provision_id}"
        ]
    EOF
rescue StandardError => e
    STDERR.puts e.to_s
    exit(-1)
end
